server:
  port: ${APP_PORT:9006}
  error:
    include-message: always

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-components: always
  health:
    defaults:
      enabled: false
    rabbit:
      enabled: true
    db:
      enabled: true
    redis:
      enabled: true

spring:
  application:
    name: staff-service
  convenient:
    rpc:
      rabbitmq:
        queue: staff-service-queue
        reply-queue-prefix: staff-service-reply-queue
        exchange: rpc-exchange
        replyTimeout: 5000
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    publisher-confirm-type: correlated
    publisher-returns: true
  sleuth:
    messaging:
      rabbit:
        enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${DB_NAME:staff_service_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: db/db.changelog-master.yaml
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

logging:
  level:
    root: INFO